name: 编译

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  deploy:
    concurrency: ci-${{ github.ref }}

    name: 部署

    runs-on: ubuntu-latest
    steps:
      - name: 检查
        uses: actions/checkout@v3

      - name: 编译 .scss 文件
        uses: gha-utilities/sass-build@v0.5.1
        with:
          source: |
            Backrooms/component-carousel-css/main.scss
            Backrooms/component-iets/main.scss
            Backrooms/component-level-class/main.scss
            Backrooms/component-tr-translation/main.scss
            Backrooms/crom-search-tag-list/main.scss
            Backrooms/entity-c-459/main.scss
            Backrooms/pw-encoder/main.scss
            Backrooms/start/main.scss
            Backrooms/theme-fandom-theme/fandom-theme-level.scss
            Backrooms/theme-defect/main.scss
            Heros_adventure/component-item-table/main.scss
            Heros_adventure/component-theme/image.scss
            Heros_adventure/component-theme/main.scss
            Heros_adventure/start/main.scss
            Oblivion_override/component-theme/main.scss
            Oblivion_override/dev-blogs/main.scss
            Oblivion_override/start/main.scss
            SCP/theme-sci-fi/main.scss
            SCP/theme-share-future-community/main.scss
            Enter_the_Gungeon/component-infobox/main.scss
            Enter_the_Gungeon/component-infotable/main.scss
            Enter_the_Gungeon/component-preview-box/main.scss
            Enter_the_Gungeon/component-theme/main.scss
          destination: |
            Backrooms/component-carousel-css/main.css
            Backrooms/component-iets/main.css
            Backrooms/component-level-class/main.css
            Backrooms/component-tr-translation/main.css
            Backrooms/crom-search-tag-list/main.css
            Backrooms/entity-c-459/main.css
            Backrooms/pw-encoder/main.css
            Backrooms/start/main.css
            Backrooms/theme-fandom-theme/fandom-theme-level.css
            Backrooms/theme-defect/main.css
            Heros_adventure/component-item-table/main.css
            Heros_adventure/component-theme/image.css
            Heros_adventure/component-theme/main.css
            Heros_adventure/start/main.css
            Oblivion_override/component-theme/main.css
            Oblivion_override/dev-blogs/main.css
            Oblivion_override/start/main.css
            SCP/theme-sci-fi/main.css
            SCP/theme-share-future-community/main.css
            Enter_the_Gungeon/component-infobox/main.css
            Enter_the_Gungeon/component-infotable/main.css
            Enter_the_Gungeon/component-preview-box/main.css
            Enter_the_Gungeon/component-theme/main.css
          outputStyle: expanded
          indentWidth: 4

      - name: Autoprefixer
        run: |
          npm install postcss postcss-cli autoprefixer
          npx postcss Backrooms/**/*.css -u autoprefixer -r
          npx postcss Heros_adventure/**/*.css -u autoprefixer -r
          npx postcss Oblivion_override/**/*.css -u autoprefixer -r
          npx postcss SCP/**/*.css -u autoprefixer -r
          npx postcss Enter_the_Gungeon/**/*.css -u autoprefixer -r
          rm -r node_modules/ .gitignore package-lock.json package.json

      - name: 部署至 GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: "gh-pages"
          folder: "."
